### ISSUE TITLE
Please add a gitee mirror

### ISSUE THREAD

**Issue by pzc2004** [Zjl37/planeFight2#1]
The Github was quite slow when I downloaded the project.So why not add a [gitee](https://gitee.com/) mirror?

**Comment by Zjl37** [comment]
1. There is now [a gitee mirror](https://gitee.com/hassium/planeFight2) maintained by @orz001 ([hassium on gitee](https://gitee.com/hassium)), go check it out! As for me, I do not plan to utilize gitee for now.
2. GitHub is not that slow here, actually If you can access through `git clone ....git`, it's just way faster than the download approach.
